=== eqdaw04/eqdaw04/Programa Compilado/XML/DTD-Jornada-en-curso.dtd
<!ELEMENT jornada-en-curso (fecha_expiracion, partido*)>
    <!ATTLIST jornada-en-curso
                id_jornada CDATA #REQUIRED>
<!ELEMENT fecha_expiracion (#PCDATA)>
        <!ELEMENT partido (fecha, hora, lugar ,equipo+)>
        <!ATTLIST partido
                id_partido CDATA #REQUIRED>
        <!ELEMENT fecha (#PCDATA)>
        <!ELEMENT hora (#PCDATA)>
        <!ELEMENT lugar (#PCDATA)>

        <!ELEMENT equipo (nombre, comentario?, puntuacion, visitante)>
        <!ATTLIST equipo
                id_equipo CDATA #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT comentario (#PCDATA)>
        <!ELEMENT puntuacion (#PCDATA)>
        <!ELEMENT visitante (#PCDATA)>

=== eqdaw04/eqdaw04/Programa/E_Sport/XML/XML-Jornada-en-curso.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE jornada-en-curso SYSTEM "DTD-Jornada-en-curso.dtd">
<jornada-en-curso id_jornada="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="XSD-Jornada-en-curso.xsd">
    <fecha_expiracion> 2018-04-26 </fecha_expiracion>
    <partido id_partido="1">

        <fecha>2018-02-10</fecha>
        <hora>10:00</hora>
        <lugar>Arriaga</lugar>

        <equipo id_equipo="1">
            <nombre>Equipo1</nombre>
            <comentario>blablabla</comentario>
            <puntuacion>5</puntuacion>
            <visitante>false</visitante>
        </equipo>

        <equipo id_equipo="2">
            <nombre>Equipo1</nombre>
            <comentario>blablabla</comentario>
            <puntuacion>5</puntuacion>
            <visitante>true</visitante>
        </equipo>

    </partido>

    <partido id_partido="2">

        <fecha>2018-02-10</fecha>
        <hora>10:00</hora>
        <lugar>Arriaga</lugar>

        <equipo id_equipo="1">
            <nombre>Equipo1</nombre>
            <comentario>blablabla</comentario>
            <puntuacion>5</puntuacion>
            <visitante>false</visitante>
        </equipo>

        <equipo id_equipo="2">
            <nombre>Equipo1</nombre>
            <comentario>blablabla</comentario>
            <puntuacion>5</puntuacion>
            <visitante>true</visitante>
        </equipo>

    </partido>
</jornada-en-curso>
