=== eqdaw04/eqdaw04/Programa/XML/XSD-Clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clasificacion" type="tipo_clasificacion"/>

<xs:complexType name="tipo_clasificacion">
    <xs:sequence>
        <xs:element name="fecha_expiracion" type="xs:date"/>
        <xs:element name="equipo" type="tipo_equipo" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tipo_equipo">
    <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="puntuacion" type="xs:int"/>
    </xs:sequence>
<xs:attribute name="id_equipo" type="xs:int"/>
</xs:complexType>




</xs:schema>

=== eqdaw04/eqdaw04/Programa/XML/XML-Clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clasificacion SYSTEM "DTD-Clasificacion.dtd">
<clasificacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD-Clasificacion.xsd">
    <fecha_expiracion> 2019-03-15 </fecha_expiracion>
    <equipo id_equipo="2">
        <nombre> Equipo2 </nombre>
        <puntuacion>150</puntuacion>
    </equipo>
    <equipo id_equipo="1">
        <nombre> Equipo1 </nombre>
        <puntuacion>135</puntuacion>
    </equipo>
    <equipo id_equipo="4">
        <nombre> Equipo4 </nombre>
        <puntuacion>110</puntuacion>
    </equipo>
    <equipo id_equipo="3">
        <nombre> Equipo3 </nombre>
        <puntuacion>104</puntuacion>
    </equipo>
    <equipo id_equipo="5">
        <nombre> Equipo5 </nombre>
        <puntuacion>98</puntuacion>
    </equipo>
</clasificacion>
